import turtle
m = turtle.Turtle()
m.speed(0)
m.pensize(10)
m.pencolor("blue")
m.circle(60)
m.penup()
m.goto(128,0)
m.down()
m.pencolor("black")
m.circle(60)
m.penup()
m.goto(189,90)
m.down()
m.pencolor("green")
m.circle(60)
m.penup()
m.goto(65,90)
m.down()
m.pencolor("yellow")
m.circle(60)
m.penup()
m.goto(-59,90)
m.down()
m.pencolor("red")
m.circle(60)
turtle.done()